# Generated by Django 5.0.4 on 2024-04-18 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dropdown_field', models.CharField(choices=[('purchased', 'Purchased'), ('sold', 'Sold'), ('hidden', 'Hidden')], default='purchased', max_length=20)),
                ('Year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025)])),
                ('Make', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('VIN', models.CharField(max_length=20)),
                ('PurchaseDate', models.DateField()),
                ('PurchasePrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('PurchasedFrom', models.CharField(max_length=200)),
                ('SoldDate', models.DateField()),
                ('SoldPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('SoldTo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('VehicleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite.vehicleinformation')),
            ],
        ),
    ]
