# Generated by Django 5.0.4 on 2024-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='PurchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='PurchasePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='PurchasedFrom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='SoldDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='SoldPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinformation',
            name='SoldTo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
