# Generated by Django 5.0.4 on 2024-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite', '0002_alter_vehicleinformation_purchasedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinformation',
            name='LockVehicle',
            field=models.BooleanField(default=False),
        ),
    ]
